services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_BASE_URL=http://localhost
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - game-network

  sala1:
    build: ./game-server
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=development
    volumes:
      - ./game-server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - game-network

  sala2:
    build: ./game-server
    ports:
      - "4001:4000"
    environment:
      - PORT=4000
      - NODE_ENV=development
    volumes:
      - ./game-server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - game-network

networks:
  game-network:
    driver: bridge
