services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_GAME_SERVER_URL=https://football-online-3d.dantecollazzi.com
      - REACT_APP_ROOMS=1,2
      - REACT_APP_ROOM_PREFIX=room
    networks:
      - game-network

  game-server:
    build: ./game-server
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    networks:
      - game-network

networks:
  game-network:
    driver: bridge
